#!/usr/bin/env bash
# dev-asu.sh — Run the ASU server locally for development and testing.
#
# This script:
#   1. Ensures a Redis instance is running (starts one via podman if needed)
#   2. Writes a development asu.toml into the ASU repo directory
#   3. Installs dependencies with uv and starts the FastAPI dev server
#
# Requirements: uv, podman
#
# Environment variables:
#   ASU_DIR  — path to the local ASU repo checkout (default: $HOME/repos/asu)

set -euo pipefail

ASU_DIR="${ASU_DIR:-$HOME/repos/asu}"

# --- Verify ASU repo exists ---
if [[ ! -d "$ASU_DIR" ]]; then
  echo "Error: ASU repo not found at $ASU_DIR"
  echo "Set ASU_DIR to point to your local checkout of the ASU application repo."
  exit 1
fi

# --- Ensure Redis is running ---
REDIS_CONTAINER="dev-redis"

if podman container exists "$REDIS_CONTAINER" 2>/dev/null; then
  if [[ "$(podman inspect -f '{{.State.Running}}' "$REDIS_CONTAINER" 2>/dev/null)" != "true" ]]; then
    echo "Starting existing Redis container..."
    podman start "$REDIS_CONTAINER"
  else
    echo "Redis is already running."
  fi
else
  echo "Starting a new Redis container ($REDIS_CONTAINER)..."
  podman run -d --name "$REDIS_CONTAINER" \
    -p 127.0.0.1:6379:6379 \
    docker.io/redis/redis-stack-server:latest
fi

# --- Write development asu.toml ---
DEV_TOML="$ASU_DIR/asu.toml"
echo "Writing development config to $DEV_TOML"

cat > "$DEV_TOML" <<'EOF'
# ASU Server Configuration — development overrides
# Generated by dev-asu.sh; do not commit this file.

upstream_url = "https://raw.githubusercontent.com/Ogglord/openwrt-imagebuilder-mt6000/releases"
base_container = "ghcr.io/ogglord/openwrt-imagebuilder"
branches_url = "https://raw.githubusercontent.com/Ogglord/openwrt-imagebuilder-mt6000/releases/branches.json"
log_level = "DEBUG"
EOF

# --- Install dependencies and start the dev server ---
echo "Installing dependencies and starting ASU dev server..."
cd "$ASU_DIR"
uv sync --extra dev
exec uv run fastapi dev asu/main.py
