#!/usr/bin/env bash
# dev-asu.sh — Run the ASU server locally for development and testing.
#
# This script:
#   1. Ensures a Redis instance is running (starts one via podman if needed)
#   2. Writes a development asu.toml into the ASU repo directory
#   3. Installs dependencies with uv and starts the FastAPI dev server
#
# Requirements: uv, podman
#
# Environment variables:
#   ASU_DIR  — path to the local ASU repo checkout (default: $HOME/repos/asu)

set -euo pipefail

ASU_DIR="${ASU_DIR:-$HOME/repos/asu}"

# --- Verify ASU repo exists ---
if [[ ! -d "$ASU_DIR" ]]; then
  echo "Error: ASU repo not found at $ASU_DIR"
  echo "Set ASU_DIR to point to your local checkout of the ASU application repo."
  exit 1
fi

# --- Ensure Redis is running ---
REDIS_CONTAINER="dev-asu-redis"
REDIS_PORT=6399  # avoid conflicting with production Redis on 6379

if podman container exists "$REDIS_CONTAINER" 2>/dev/null; then
  if [[ "$(podman inspect -f '{{.State.Running}}' "$REDIS_CONTAINER" 2>/dev/null)" != "true" ]]; then
    echo "Starting existing Redis container..."
    podman start "$REDIS_CONTAINER"
  else
    echo "Redis is already running on port $REDIS_PORT."
  fi
else
  echo "Starting a new Redis container ($REDIS_CONTAINER) on port $REDIS_PORT..."
  podman run -d --name "$REDIS_CONTAINER" \
    -p "127.0.0.1:${REDIS_PORT}:6379" \
    docker.io/redis:alpine
fi

# --- Write development asu.toml ---
DEV_TOML="$ASU_DIR/asu.toml"
echo "Writing development config to $DEV_TOML"

PUBLIC_DIR="$ASU_DIR/.dev-data"
mkdir -p "$PUBLIC_DIR/store"

cat > "$DEV_TOML" <<EOF
# ASU Server Configuration — development overrides
# Generated by dev-asu.sh; do not commit this file.

upstream_url = "https://raw.githubusercontent.com/Ogglord/openwrt-imagebuilder-mt6000/releases"
base_container = "ghcr.io/ogglord/openwrt-imagebuilder"
branches_url = "https://raw.githubusercontent.com/Ogglord/openwrt-imagebuilder-mt6000/releases/branches.json"
redis_url = "redis://localhost:${REDIS_PORT}"
public_path = "${PUBLIC_DIR}"
log_level = "DEBUG"

# Override default upstream branches — all loaded from branches_url
[branches]
EOF

# --- Install dependencies and start the dev server ---
echo "Installing dependencies..."
cd "$ASU_DIR"
uv sync --extra dev

DEV_PORT=8001
BASE="http://127.0.0.1:${DEV_PORT}"

echo "Starting ASU dev server on ${BASE} ..."
uv run fastapi dev asu/main.py --host 0.0.0.0 --port "$DEV_PORT" &
SERVER_PID=$!

# --- Health checks ---
echo "Waiting for server to become ready..."
MAX_WAIT=30
ELAPSED=0
while ! curl -o /dev/null -fsS -m 2 "$BASE/" 2>/dev/null; do
  if ! kill -0 "$SERVER_PID" 2>/dev/null; then
    echo "Server process exited unexpectedly"
    exit 1
  fi
  if [[ $ELAPSED -ge $MAX_WAIT ]]; then
    echo "Server did not respond within ${MAX_WAIT}s"
    kill "$SERVER_PID" 2>/dev/null
    exit 1
  fi
  sleep 1
  ELAPSED=$((ELAPSED + 1))
done

ALL_OK=true
for PATH_CHECK in "/" "/json/v1/overview.json" "/json/v1/branches.json"; do
  CODE=$(curl -o /dev/null -sS -m 5 -w "%{http_code}" "${BASE}${PATH_CHECK}" 2>/dev/null) || CODE="ERR"
  if [[ "$CODE" =~ ^2 ]]; then
    echo "  OK   ${CODE}  ${PATH_CHECK}"
  else
    echo "  FAIL ${CODE}  ${PATH_CHECK}"
    ALL_OK=false
  fi
done

# Show loaded branches
BRANCHES=$(curl -sS -m 5 "${BASE}/json/v1/overview.json" 2>/dev/null | \
  python3 -c "
import json,sys
data = json.load(sys.stdin)
custom = [k for k in data.get('branches',{}) if k not in ('SNAPSHOT','25.12','24.10','23.05','22.03','21.02')]
print(', '.join(custom) if custom else '(none)')
" 2>/dev/null) || BRANCHES="(failed to fetch)"
echo ""
echo "  Branches: ${BRANCHES}"

if $ALL_OK; then
  echo ""
  echo "=== Dev server ready at ${BASE} ==="
  echo "    Docs: ${BASE}/docs"
  echo "    Press Ctrl+C to stop"
else
  echo ""
  echo "=== Dev server started with health check failures ==="
fi

# Foreground the server so Ctrl+C stops it cleanly
wait "$SERVER_PID"
